### PR TITLE
Support torch tensors

### PR DESCRIPTION
**Pull request by youben11**
Make the conversion from torch.Tensor possible through the convert_to_tensor function.

### CODE REVIEW

**Comment by justin1121** [comment]
Hey @youben11,

Looks like torch isn't being installed as a dependency. To get this to work we may need to add a requirements.txt file and install it as part of the CI dependencies installation as well as importing it into the setup.py file. This has also made me think that torch is quite a large dependency to have as part of this project. Can it be an optional dependency or do you have any other ideas around this? Thanks.

**Comment by youben11** [comment]
Yes, I only used torch directly to make the check clean as much as possible, but we can workaround this by checking both `tensor.__class__.__name__` and `tensor.__class__.__module__`. This will not require having torch installed.

Another possibility would be to try importing torch and use it to check the tensor type, if the import fails then use the above workaround.

**Comment by justin1121** [comment]
Yeah I think the second option makes sense. Can you add torch as an extras requirement?

**Comment by youben11** [comment]
Will just need to install torch on the test environment so I can add some tests around using torch tensors. Which requirement file is circleci using for installing the deps?

**Comment by justin1121** [comment]
Closing this as I think we're taking another direction. Thanks @youben11 !!!

**Pull request closed without merging**
